import { render } from "../templates/engine.js";
import type { Collection, Field } from "../core/schema-parser.js";
import type { GeneratorContext } from "../core/context.js";
import template from "../templates/prisma/route.hbs";
import openapiTemplate from "../templates/prisma/route-openapi.hbs";

function zodExpression(field: Field): string {
  let expr: string;
  switch (field.type) {
    case "text":
      expr = "z.string()";
      if (field.min !== undefined) expr += `.min(${field.min})`;
      if (field.max !== undefined) expr += `.max(${field.max})`;
      break;
    case "number":
      expr = "z.number()";
      if (field.min !== undefined) expr += `.min(${field.min})`;
      if (field.max !== undefined) expr += `.max(${field.max})`;
      break;
    case "integer":
      expr = "z.number().int()";
      if (field.min !== undefined) expr += `.min(${field.min})`;
      if (field.max !== undefined) expr += `.max(${field.max})`;
      break;
    case "boolean":
      expr = "z.boolean()";
      break;
    case "date":
      expr = 'z.string().datetime({ offset: true }).or(z.string().date())';
      break;
    case "json":
      expr = "z.any()";
      break;
    case "relation":
      expr = "z.string().min(1)";
      break;
    default:
      expr = "z.any()";
  }
  return expr;
}

export function generatePrismaRoute(
  collection: Collection,
  ctx: GeneratorContext,
): string {
  const lang = ctx.lang;
  const idConfig = collection.id;
  const idAutoGenerated =
    idConfig.type === "uuid" ||
    (idConfig.type === "integer" && idConfig.autoincrement);
  const idIsInteger = idConfig.type === "integer";

  const createFields = Object.entries(collection.fields).map(
    ([name, field]) => ({
      name,
      zodExpr: zodExpression(field),
      required: !!field.required,
      hasDefault: field.default !== undefined,
      defaultValue:
        field.default !== undefined ? JSON.stringify(field.default) : undefined,
    }),
  );

  if (!idAutoGenerated) {
    const idZodExpr = idIsInteger ? "z.number().int()" : "z.string().min(1)";
    createFields.unshift({
      name: "id",
      zodExpr: idZodExpr,
      required: true,
      hasDefault: false,
      defaultValue: undefined,
    });
  }

  const validFieldsList = [
    ...Object.keys(collection.fields),
    "id",
    "created_at",
    "updated_at",
  ];

  const relations = Object.entries(collection.fields)
    .filter(([, f]) => f.type === "relation" && f.collection)
    .map(([name, f]) => ({ fieldName: name, targetCollection: f.collection! }));

  const uniqueErrorCheck = 'err.code === "P2002"';
  const fkErrorCheck = 'err.code === "P2003"';

  const capitalName = collection.name.charAt(0).toUpperCase() + collection.name.slice(1);
  const singularName = capitalName.replace(/s$/, "");

  const context = {
    lang,
    validation: ctx.validation,
    collectionName: collection.name,
    capitalName,
    singularName,
    idIsInteger,
    idAutoGenerated,
    createFields,
    validFieldsJson: JSON.stringify(validFieldsList),
    relations,
    uniqueErrorCheck,
    fkErrorCheck,
  };

  return render(ctx.openapi ? openapiTemplate : template, context);
}
