import { render } from "../templates/engine.js";
import type { Collection, Field } from "../core/schema-parser.js";
import template from "../templates/routes/route.hbs";

function zodExpression(field: Field): string {
  let expr: string;
  switch (field.type) {
    case "text":
      expr = "z.string()";
      if (field.min !== undefined) expr += `.min(${field.min})`;
      if (field.max !== undefined) expr += `.max(${field.max})`;
      break;
    case "number":
      expr = "z.number()";
      if (field.min !== undefined) expr += `.min(${field.min})`;
      if (field.max !== undefined) expr += `.max(${field.max})`;
      break;
    case "integer":
      expr = "z.number().int()";
      if (field.min !== undefined) expr += `.min(${field.min})`;
      if (field.max !== undefined) expr += `.max(${field.max})`;
      break;
    case "boolean":
      expr = "z.boolean()";
      break;
    case "date":
      expr = 'z.iso.datetime().or(z.iso.date())';
      break;
    case "json":
      expr = "z.any()";
      break;
    case "relation":
      expr = "z.string().min(1)";
      break;
    default:
      expr = "z.any()";
  }
  return expr;
}

export function generateRoute(collection: Collection, lang: "ts" | "js"): string {
  const idConfig = collection.id;
  const idAutoGenerated = idConfig.type === "uuid" || (idConfig.type === "integer" && idConfig.autoincrement);
  const idIsInteger = idConfig.type === "integer";

  const createFields = Object.entries(collection.fields).map(([name, field]) => ({
    name,
    zodExpr: zodExpression(field),
    required: !!field.required,
    hasDefault: field.default !== undefined,
    defaultValue: field.default !== undefined ? JSON.stringify(field.default) : undefined,
  }));

  // If id is not auto-generated, add it as a required field in create schema
  if (!idAutoGenerated) {
    const idZodExpr = idIsInteger ? "z.number().int()" : "z.string().min(1)";
    createFields.unshift({ name: "id", zodExpr: idZodExpr, required: true, hasDefault: false, defaultValue: undefined });
  }

  const updateFields = Object.entries(collection.fields).map(([name, field]) => ({
    name,
    zodExpr: zodExpression(field),
  }));

  const validFieldsList = [
    ...Object.keys(collection.fields),
    "id", "created_at", "updated_at",
  ];

  const relations = Object.entries(collection.fields)
    .filter(([, f]) => f.type === "relation" && f.collection)
    .map(([name, f]) => ({ fieldName: name, targetCollection: f.collection! }));

  const relationImports = [...new Set(
    relations
      .map((r) => r.targetCollection)
      .filter((t) => t !== collection.name),
  )].map((name) => ({ name }));

  const context = {
    lang,
    collectionName: collection.name,
    idIsInteger,
    idAutoGenerated,
    createFields,
    updateFields,
    validFieldsJson: JSON.stringify(validFieldsList),
    relations,
    relationImports,
  };

  return render(template, context);
}
