import { render } from "../../templates/engine";
import type { Collection, GeneratorContext } from "@honora/types";
import { zodExpression } from "../../shared/zod-expression";
import template from "../../templates/drizzle/route.hbs";
import openapiTemplate from "../../templates/drizzle/route-openapi.hbs";

export function generateRoute(collection: Collection, ctx: GeneratorContext): string {
  const lang = ctx.lang;
  const idConfig = collection.id;
  const idAutoGenerated =
    idConfig.type === "uuid" ||
    (idConfig.type === "integer" && idConfig.autoincrement);
  const idIsInteger = idConfig.type === "integer";

  const createFields = Object.entries(collection.fields).map(([name, field]) => ({
    name,
    zodExpr: zodExpression(field),
    required: !!field.required,
    hasDefault: field.default !== undefined,
    defaultValue: field.default !== undefined ? JSON.stringify(field.default) : undefined,
  }));

  if (!idAutoGenerated) {
    const idZodExpr = idIsInteger ? "z.number().int()" : "z.string().min(1)";
    createFields.unshift({
      name: "id",
      zodExpr: idZodExpr,
      required: true,
      hasDefault: false,
      defaultValue: undefined,
    });
  }

  const updateFields = Object.entries(collection.fields).map(([name, field]) => ({
    name,
    zodExpr: zodExpression(field),
  }));

  const validFieldsList = [
    ...Object.keys(collection.fields),
    "id",
    "created_at",
    "updated_at",
  ];

  const relations = Object.entries(collection.fields)
    .filter(([, f]) => f.type === "relation" && f.collection)
    .map(([name, f]) => ({ fieldName: name, targetCollection: f.collection! }));

  const relationImports = [
    ...new Set(
      relations
        .map((r) => r.targetCollection)
        .filter((t) => t !== collection.name),
    ),
  ].map((name) => ({ name }));

  const { driver } = ctx;
  const uniqueErrorCheck =
    driver === "postgres"
      ? 'err.code === "23505"'
      : driver === "mysql"
        ? 'err.code === "ER_DUP_ENTRY"'
        : 'err.message?.includes("UNIQUE constraint")';

  const fkErrorCheck =
    driver === "postgres"
      ? 'err.code === "23503"'
      : driver === "mysql"
        ? 'err.code === "ER_ROW_IS_REFERENCED_2"'
        : 'err.message?.includes("FOREIGN KEY constraint failed")';

  const capitalName = collection.name.charAt(0).toUpperCase() + collection.name.slice(1);
  const singularName = capitalName.replace(/s$/, "");

  const context = {
    lang,
    driver,
    validation: ctx.validation,
    collectionName: collection.name,
    capitalName,
    singularName,
    idIsInteger,
    idAutoGenerated,
    createFields,
    updateFields,
    validFieldsJson: JSON.stringify(validFieldsList),
    relations,
    relationImports,
    uniqueErrorCheck,
    fkErrorCheck,
  };

  return render(ctx.openapi ? openapiTemplate : template, context);
}
