import { render } from "../../templates/engine";
import type { Collection, GeneratorContext } from "@honora/types";
import { zodExpression } from "../../shared/zod-expression";
import { buildAllowHeader } from "../../shared/allow-header";
import template from "../../templates/prisma/route.hbs";
import openapiTemplate from "../../templates/prisma/route-openapi.hbs";

export function generatePrismaRoute(collection: Collection, ctx: GeneratorContext): string {
  const lang = ctx.lang;
  const idConfig = collection.id;
  const idAutoGenerated =
    idConfig.type === "uuid" ||
    (idConfig.type === "integer" && idConfig.autoincrement);
  const idIsInteger = idConfig.type === "integer";

  const createFields = Object.entries(collection.fields).map(([name, field]) => ({
    name,
    zodExpr: zodExpression(field),
    required: !!field.required,
    hasDefault: field.default !== undefined,
    defaultValue: field.default !== undefined ? JSON.stringify(field.default) : undefined,
  }));

  if (!idAutoGenerated) {
    const idZodExpr = idIsInteger ? "z.number().int()" : "z.string().min(1)";
    createFields.unshift({
      name: "id",
      zodExpr: idZodExpr,
      required: true,
      hasDefault: false,
      defaultValue: undefined,
    });
  }

  const validFieldsList = [
    ...Object.keys(collection.fields),
    "id",
    "created_at",
    "updated_at",
  ];

  const relations = Object.entries(collection.fields)
    .filter(([, f]) => f.type === "relation" && f.collection)
    .map(([name, f]) => ({ fieldName: name, targetCollection: f.collection! }));

  const uniqueErrorCheck = 'err.code === "P2002"';
  const fkErrorCheck = 'err.code === "P2003"';

  const capitalName = collection.name.charAt(0).toUpperCase() + collection.name.slice(1);
  const singularName = capitalName.replace(/s$/, "");

  const methods = new Set<string>(collection.methods);

  const context = {
    lang,
    validation: ctx.validation,
    collectionName: collection.name,
    capitalName,
    singularName,
    idIsInteger,
    idAutoGenerated,
    createFields,
    validFieldsJson: JSON.stringify(validFieldsList),
    relations,
    uniqueErrorCheck,
    fkErrorCheck,
    hasGet: methods.has("get"),
    hasGetById: methods.has("getId"),
    hasPost: methods.has("post"),
    hasPut: methods.has("put"),
    hasPatch: methods.has("patch"),
    hasDelete: methods.has("delete"),
    hasOptions: methods.has("options"),
    allowedMethods: buildAllowHeader(methods, false),
    allowedIdMethods: buildAllowHeader(methods, true),
  };

  return render(ctx.openapi ? openapiTemplate : template, context);
}
